# Connexion à la base de données (Assurez-vous d'avoir créé une base nommée gestion_ressources_db dans MySQL)
spring.datasource.url=jdbc:mysql://localhost:3307/gestion_ressources_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration du serveur Tomcat
server.port=8081
