
### Test de la connexion (Vérifier si le serveur tourne)
GET http://localhost:8081/api/test

###

### 1. Créer le département (Obligatoire avant l'enseignant)
POST http://localhost:8081/api/departements
Content-Type: application/json

{
  "nom": "Département Informatique",
  "budget": 50000.0
}

###

### 2. Créer le type de ressource
POST http://localhost:8081/api/types-ressources
Content-Type: application/json

{
  "code": "ORDINATEUR",
  "libelle": "Ordinateur",
  "estStandard": true
}